export type VncServerProfile = 'speed' | 'balanced' | 'quality';

export const DEFAULT_VNC_SERVER_PROFILE: VncServerProfile = 'balanced';
export const VNC_SERVER_PROFILES: VncServerProfile[] = ['speed', 'balanced', 'quality'];

interface VncServerEncodingPreset {
  frameRate: number;
  minQuality: number;
  maxQuality: number;
  losslessQuality: number;
  jpegQuality: number;
  webpQuality: number;
  videoTime: number;
  videoArea: string;
  videoOutTime: number;
}

const VNC_SERVER_ENCODING_PRESETS: Record<VncServerProfile, VncServerEncodingPreset> = {
  speed: {
    frameRate: 15,
    minQuality: 3,
    maxQuality: 5,
    losslessQuality: 8,
    jpegQuality: 4,
    webpQuality: 4,
    videoTime: 3,
    videoArea: '30%',
    videoOutTime: 2,
  },
  balanced: {
    frameRate: 24,
    minQuality: 5,
    maxQuality: 7,
    losslessQuality: 9,
    jpegQuality: 6,
    webpQuality: 6,
    videoTime: 5,
    videoArea: '45%',
    videoOutTime: 3,
  },
  quality: {
    frameRate: 30,
    minQuality: 7,
    maxQuality: 8,
    losslessQuality: 10,
    jpegQuality: 8,
    webpQuality: 8,
    videoTime: 5,
    videoArea: '45%',
    videoOutTime: 3,
  },
};

export function normalizeVncServerProfile(value: unknown): VncServerProfile {
  if (typeof value === 'string' && VNC_SERVER_PROFILES.includes(value as VncServerProfile)) {
    return value as VncServerProfile;
  }
  throw new Error('VNC 服务端档位不合法');
}

export function normalizeOptionalVncServerProfile(value: unknown): VncServerProfile {
  if (value == null || value === '') return DEFAULT_VNC_SERVER_PROFILE;
  return normalizeVncServerProfile(value);
}

export function kasmVncServerProfileYaml(profile: VncServerProfile): string {
  const preset = VNC_SERVER_ENCODING_PRESETS[profile];
  return [
    '# Generated by WechatOnCloud. Do not edit manually.',
    `# Profile: ${profile}`,
    'runtime_configuration:',
    '  allow_client_to_override_kasm_server_settings: false',
    '  allow_override_standard_vnc_server_settings: true',
    '  allow_override_list:',
    '    - pointer.enabled',
    '    - data_loss_prevention.clipboard.server_to_client.enabled',
    '    - data_loss_prevention.clipboard.client_to_server.enabled',
    '    - data_loss_prevention.clipboard.server_to_client.primary_clipboard_enabled',
    'encoding:',
    `  max_frame_rate: ${preset.frameRate}`,
    '  full_frame_updates: none',
    '  rect_encoding_mode:',
    `    min_quality: ${preset.minQuality}`,
    `    max_quality: ${preset.maxQuality}`,
    `    consider_lossless_quality: ${preset.losslessQuality}`,
    '    rectangle_compress_threads: auto',
    '  video_encoding_mode:',
    `    jpeg_quality: ${preset.jpegQuality}`,
    `    webp_quality: ${preset.webpQuality}`,
    '    max_resolution:',
    '      width: 1920',
    '      height: 1080',
    '    enter_video_encoding_mode:',
    `      time_threshold: ${preset.videoTime}`,
    `      area_threshold: "${preset.videoArea}"`,
    '    exit_video_encoding_mode:',
    `      time_threshold: ${preset.videoOutTime}`,
    '    scaling_algorithm: progressive_bilinear',
    '  compare_framebuffer: auto',
    '  zrle_zlib_level: auto',
    '  hextile_improved_compression: true',
    '',
  ].join('\n');
}
