#!/bin/bash
set -e

if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ] && [ -z "${WOC_BROWSER_DBUS_SESSION_STARTED:-}" ]; then
  export WOC_BROWSER_DBUS_SESSION_STARTED=1
  exec dbus-run-session -- "$0" "$@"
fi

# shellcheck source=/dev/null
. /woc/app-defs.sh
woc_apply_software_rendering_env
mapfile -t chromium_flags < <(woc_chromium_software_flags)

chromium_flags+=(
  --no-first-run
  --no-default-browser-check
  --start-maximized
  --password-store=basic
  --disable-background-networking
  --disable-component-update
  --disable-sync
  --disable-domain-reliability
  --user-data-dir=/config/chromium
)

exec /usr/bin/chromium "${chromium_flags[@]}" "$@"
