#!/usr/bin/with-contenv bash
# /custom-cont-init.d 钩子（04）：把面板传入的 KasmVNC 服务端基础配置写入数据卷。
set -e

CONFIG_DIR=/config/.vnc
CONFIG_FILE="${CONFIG_DIR}/kasmvnc.yaml"

mkdir -p "$CONFIG_DIR"

if [ -n "${WOC_VNC_SERVER_CONFIG_YAML_B64:-}" ]; then
    printf '%s' "$WOC_VNC_SERVER_CONFIG_YAML_B64" | base64 -d > "${CONFIG_FILE}.tmp"
else
    cat > "${CONFIG_FILE}.tmp" <<'YAML'
# Generated by WechatOnCloud. Do not edit manually.
# Profile: balanced
runtime_configuration:
  allow_client_to_override_kasm_server_settings: true
  allow_override_standard_vnc_server_settings: true
  allow_override_list:
    - pointer.enabled
    - data_loss_prevention.clipboard.server_to_client.enabled
    - data_loss_prevention.clipboard.client_to_server.enabled
    - data_loss_prevention.clipboard.server_to_client.primary_clipboard_enabled
encoding:
  max_frame_rate: 24
  full_frame_updates: none
  rect_encoding_mode:
    min_quality: 5
    max_quality: 7
    consider_lossless_quality: 9
    rectangle_compress_threads: auto
  video_encoding_mode:
    jpeg_quality: 6
    webp_quality: 6
    max_resolution:
      width: 1920
      height: 1080
    enter_video_encoding_mode:
      time_threshold: 5
      area_threshold: "45%"
    exit_video_encoding_mode:
      time_threshold: 3
    scaling_algorithm: progressive_bilinear
  compare_framebuffer: auto
  zrle_zlib_level: auto
  hextile_improved_compression: true
YAML
fi

mv -f "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
chown -R "${PUID:-1000}:${PGID:-1000}" "$CONFIG_DIR" 2>/dev/null || true
echo "[woc-vnc] KasmVNC 服务端基础配置已写入"
